services:
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    env_file:
      - ./env/backend.env
    depends_on:
      - postgres
    

  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    stdin_open: true
    tty: true
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    env_file:
      - ./env/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5431:5432'

volumes:
  postgres-data: